// VisWin.h
//
// Copyright ?2000 Microsoft Corporation, All Rights Reserved

#pragma once


#define WIN32_LEAN_AND_MEAN
#define VC_EXTRALEAN		// Exclude rarely-used stuff from Windows headers


// VisLocalInfo.h is generated by the VisLocalInfo project in the Vision SDK.
// If you get an error that VisLocalInfo.h does not exist, you need to build
// the VisLocalInfo.h project (or double-click on the VisLocalInfo.bat file
// in the VisLocalInfo directory).
#include "VisLocalInfo.h"


#ifndef _AFXDLL

#include <windows.h>

#else // _AFXDLL

#include <afxwin.h>         // MFC core and standard components

#include <afxext.h>         // MFC extensions
#ifndef _AFX_NO_AFXCMN_SUPPORT
#include <afxcmn.h>			// MFC support for Windows 95 Common Controls
#endif // _AFX_NO_AFXCMN_SUPPORT

#endif // _AFXDLL


#ifdef __AFX_H__  // (__AFX_H__ is defined when we're using MFC.)
	#define VIS_IS_USING_MFC
#endif // __AFX_H__  // (__AFX_H__ is defined when we're using MFC.)


#include "VisMFCTypes.h"